# Generated by Django 6.0.2 on 2026-02-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('nationallty', models.CharField(max_length=100)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
    ]
