# Generated by Django 6.0.2 on 2026-02-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('discribtion', models.TextField()),
                ('spread_date', models.DateField()),
                ('number_pages', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('category', models.ManyToManyField(to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateField()),
                ('reading_status', models.CharField(choices=[('reading', 'في القراءة'), ('completed', 'مكتمل'), ('paused', 'معلق'), ('abandoned', 'مُترَك')], default='reading', help_text='حالة القراءة الحالية للكتاب', max_length=20)),
                ('books', models.ManyToManyField(to='books.book')),
            ],
        ),
    ]
