# Generated by Django 6.0.2 on 2026-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_messages_reading_status_book_reading_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reading_status',
        ),
        migrations.AddField(
            model_name='messages',
            name='reading_status',
            field=models.CharField(choices=[('reading', 'reading'), ('completed', 'completed'), ('paused', 'paused'), ('abandoned', 'abandoned')], default='reading', help_text='حالة القراءة الحالية للكتاب', max_length=20),
        ),
    ]
