# Generated by Django 6.0.2 on 2026-02-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_messages_reading_status_book_reading_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='books',
        ),
    ]
