# Generated by Django 6.0.2 on 2026-02-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_favoritebooks_delete_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_mark_featured', 'Can add a feature')]},
        ),
    ]
